#Import and initialization:

In [8]:
from google.colab import drive
import sys
import os
import pandas as pd
import numpy as np
drive.mount('/content/drive')
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer, util
import pickle
path = '/content/drive/MyDrive/Semantics In Intelligent Information Access/'
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
!pip install openai
import os
import openai
openai.api_key = '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' #generate this key using an openai account.

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
#embedding_type = 'exnovo'
embedding_type = 'stored'
dataset = pd.read_csv("/content/drive/MyDrive/Semantics In Intelligent Information Access/dataset_covered_recipes.csv",sep=';')
dataset_sustainble =  dataset.loc[np.where(dataset['SUSTAINABILITY'].eq('HIGH'))]
dataset_sustainble.reset_index(inplace = True,drop = True)
dataset_mid_sustainble =  dataset.loc[np.where(dataset['SUSTAINABILITY'].eq('MEDIUM'))]
dataset_mid_sustainble.reset_index(inplace = True,drop = True)

if(embedding_type == 'exnovo'):  
  embedding_sus_recipes = model.encode(dataset_sustainble['ingredients'])
  embedding_mid_sus_recipes = model.encode(dataset_mid_sustainble['ingredients'])
  with open(path+'embedding_sus_recipes.pkl', "wb") as fOut:
    pickle.dump({'sentences': dataset_sustainble['ingredients'], 'embeddings': embedding_sus_recipes}, fOut, protocol=pickle.HIGHEST_PROTOCOL)
  with open(path+'embedding_mid_sus_recipes.pkl', "wb") as fOut:
    pickle.dump({'sentences': dataset_mid_sustainble['ingredients'], 'embeddings': embedding_mid_sus_recipes}, fOut, protocol=pickle.HIGHEST_PROTOCOL)

if(embedding_type == 'stored'):
  with open(path+'embedding_sus_recipes.pkl', "rb") as fIn:
    stored_data_sus_recipes = pickle.load(fIn)
    embedding_sus_recipes = stored_data_sus_recipes['embeddings']
  with open(path+'embedding_mid_sus_recipes.pkl', "rb") as fIn:
    stored_data_mid_sus_recipes = pickle.load(fIn)
    embedding_mid_sus_recipes = stored_data_mid_sus_recipes['embeddings']

#Test

In [10]:
my_ingredients = 'oats,banana,milk'
embedding_ing = model.encode(my_ingredients)
sus_scores = []  
sus_scores = util.pytorch_cos_sim(embedding_ing, embedding_sus_recipes).flatten()
print(sus_scores)
sus_sorted = sus_scores.argsort()[-3:]
print(sus_scores[sus_sorted])
sus_results = dataset_sustainble.loc[sus_sorted]
sus_results

tensor([0.0759, 0.2650, 0.2650,  ..., 0.6454, 0.3984, 0.4800])
tensor([0.8304, 0.8824, 0.9423])


recipe_id                                      title  \
487       35477                          Survival Necklace   
1951      50516                 Strawberry Banana Smoothie   
1728       2818  Oatmeal and Bananas Breakfast (Baby Food)   

                                                    url  \
487   http://www.food.com/recipe/survival-necklace-9...   
1951  http://www.kraftrecipes.com/recipes/strawberry...   
1728  http://www.food.com/recipe/oatmeal-and-bananas...   

                              ingredients SUSTAINABILITY  
487                       banana,oat meal           HIGH  
1951  cow milk,banana,strawberry,oat meal           HIGH  
1728                  oat,cow milk,banana           HIGH

In [11]:
mid_sus_scores = []  
mid_sus_scores = util.pytorch_cos_sim(embedding_ing, embedding_mid_sus_recipes).flatten()
print(mid_sus_scores)
mid_sus_sorted = mid_sus_scores.argsort()[-3:]
print(mid_sus_scores[mid_sus_sorted])
mid_sus_results = dataset_mid_sustainble.loc[mid_sus_sorted]
mid_sus_results

tensor([0.6187, 0.4644, 0.6124,  ..., 0.4748, 0.4394, 0.5109])
tensor([0.7735, 0.7783, 0.7811])


recipe_id                               title  \
5837      23711  Oatmeal With Blueberries and Cream   
8495      39484                Apple Butter Oatmeal   
1461      45835            Fruit and Malt Oat Shake   

                                                    url  \
5837  http://www.food.com/recipe/oatmeal-with-bluebe...   
8495  http://www.food.com/recipe/apple-butter-oatmea...   
1461  http://www.food.com/recipe/fruit-and-malt-oat-...   

                                            ingredients SUSTAINABILITY  
5837                       oat,cream,cow milk,blueberry         MEDIUM  
8495                                oat,cow milk,butter         MEDIUM  
1461  oat,cow milk,banana,semi-sweet chocolate bakin...         MEDIUM

In [14]:
sus_max_index = sus_sorted[-1]
mid_sus_max_index = mid_sus_sorted[-1]
response = openai.Completion.create(
  model="text-davinci-003",
  prompt="i'm building a recommender system for recipes. The user has selected the following ingredients: "+my_ingredients+".\nsuppose we have a medium sustainable recipe "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['title'].values[0]+" composed of "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['ingredients'].values[0]+" which is readable at url "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['url'].values[0]+" and a fully stustainable recipe "+dataset_sustainble.loc[[sus_max_index]]['title'].values[0]+" composed of "+dataset_sustainble.loc[[sus_max_index]]['ingredients'].values[0]+" which is readable at url  "+dataset_sustainble.loc[[sus_max_index]]['url'].values[0]+" . \nWrite a text that suggest, reffering to the user's ingredients, to consume the first recipe and the second if he/she prefer a more sustainable recipe.\nYou must point out that the second recipe is more sustainable.\nBoth suggestion must refer to the url in order to made possible for user to read the full recipes.\nIf you refer to recipes ingredients use only the ones listed.",
  temperature=0.8,
  max_tokens=1200
)
print(response['choices'][0]['text'])




If you're looking to make a delicious, nutritious breakfast with your ingredients of oats, banana, and milk, you should try this delicious Fruit and Malt Oat Shake! This recipe is composed of oats, cow milk, banana, and semi-sweet chocolate baking chips and can be found at http://www.food.com/recipe/fruit-and-malt-oat-shake-463414. For a more sustainable recipe, try out this Oatmeal and Bananas Breakfast (Baby Food) recipe composed of oats, cow milk, and banana at http://www.food.com/recipe/oatmeal-and-bananas-breakfast-baby-food-52539. It is a more sustainable option compared to the Fruit and Malt Oat Shake.
