#Import and initialization:

In [1]:
from google.colab import drive
import sys
import os
import pandas as pd
import numpy as np
drive.mount('/content/drive')
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer, util
import pickle
path = '/content/drive/MyDrive/Semantics In Intelligent Information Access/'
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
!pip install openai
import os
import openai
openai.api_key = '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' #generate this key using an openai account.

Mounted at /content/drive
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 40.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 65.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 19.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 86.7 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=3247d176d63b17b0470a11be0d71b5adb54cf2d4423cc777e8b8ce877c444233
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [4]:
#embedding_type = 'exnovo'
embedding_type = 'stored'
dataset = pd.read_csv("/content/drive/MyDrive/Semantics In Intelligent Information Access/dataset_covered_recipes.csv",sep=';')
dataset_sustainble =  dataset.loc[np.where(dataset['SUSTAINABILITY'].eq('HIGH'))]
dataset_sustainble.reset_index(inplace = True,drop = True)
dataset_mid_sustainble =  dataset.loc[np.where(dataset['SUSTAINABILITY'].eq('MEDIUM'))]
dataset_mid_sustainble.reset_index(inplace = True,drop = True)

if(embedding_type == 'exnovo'):  
  embedding_sus_recipes = model.encode(dataset_sustainble['ingredients'])
  embedding_mid_sus_recipes = model.encode(dataset_mid_sustainble['ingredients'])
  with open(path+'embedding_sus_recipes.pkl', "wb") as fOut:
    pickle.dump({'sentences': dataset_sustainble['ingredients'], 'embeddings': embedding_sus_recipes}, fOut, protocol=pickle.HIGHEST_PROTOCOL)
  with open(path+'embedding_mid_sus_recipes.pkl', "wb") as fOut:
    pickle.dump({'sentences': dataset_mid_sustainble['ingredients'], 'embeddings': embedding_mid_sus_recipes}, fOut, protocol=pickle.HIGHEST_PROTOCOL)

if(embedding_type == 'stored'):
  with open(path+'embedding_sus_recipes.pkl', "rb") as fIn:
    stored_data_sus_recipes = pickle.load(fIn)
    embedding_sus_recipes = stored_data_sus_recipes['embeddings']
  with open(path+'embedding_mid_sus_recipes.pkl', "rb") as fIn:
    stored_data_mid_sus_recipes = pickle.load(fIn)
    embedding_mid_sus_recipes = stored_data_mid_sus_recipes['embeddings']

#Test

In [52]:
my_ingredients = 'oats,banana,milk'
embedding_ing = model.encode(my_ingredients)
sus_scores = []  
sus_scores = util.pytorch_cos_sim(embedding_ing, embedding_sus_recipes).flatten()
print(sus_scores)
sus_sorted = sus_scores.argsort()[-3:]
print(sus_scores[sus_sorted])
sus_results = dataset_sustainble.loc[sus_sorted]
sus_results

tensor([0.0759, 0.2650, 0.2650,  ..., 0.6454, 0.3984, 0.4800])
tensor([0.8304, 0.8824, 0.9423])


recipe_id                                      title  \
487       35477                          Survival Necklace   
1951      50516                 Strawberry Banana Smoothie   
1728       2818  Oatmeal and Bananas Breakfast (Baby Food)   

                                                    url  \
487   http://www.food.com/recipe/survival-necklace-9...   
1951  http://www.kraftrecipes.com/recipes/strawberry...   
1728  http://www.food.com/recipe/oatmeal-and-bananas...   

                              ingredients SUSTAINABILITY  
487                       banana,oat meal           HIGH  
1951  cow milk,banana,strawberry,oat meal           HIGH  
1728                  oat,cow milk,banana           HIGH

In [53]:
mid_sus_scores = []  
mid_sus_scores = util.pytorch_cos_sim(embedding_ing, embedding_mid_sus_recipes).flatten()
print(mid_sus_scores)
mid_sus_sorted = mid_sus_scores.argsort()[-3:]
print(mid_sus_scores[mid_sus_sorted])
mid_sus_results = dataset_mid_sustainble.loc[mid_sus_sorted]
mid_sus_results

tensor([0.6187, 0.4644, 0.6124,  ..., 0.4748, 0.4394, 0.5109])
tensor([0.7735, 0.7783, 0.7811])


recipe_id                               title  \
5837      23711  Oatmeal With Blueberries and Cream   
8495      39484                Apple Butter Oatmeal   
1461      45835            Fruit and Malt Oat Shake   

                                                    url  \
5837  http://www.food.com/recipe/oatmeal-with-bluebe...   
8495  http://www.food.com/recipe/apple-butter-oatmea...   
1461  http://www.food.com/recipe/fruit-and-malt-oat-...   

                                            ingredients SUSTAINABILITY  
5837                       oat,cream,cow milk,blueberry         MEDIUM  
8495                                oat,cow milk,butter         MEDIUM  
1461  oat,cow milk,banana,semi-sweet chocolate bakin...         MEDIUM

In [54]:
sus_max_index = sus_sorted[-1]
mid_sus_max_index = mid_sus_sorted[-1]
response = openai.Completion.create(
  model="text-davinci-003",
  prompt="i'm buiding a recommeder system for recipes. The user have selected the following ingredients: "+my_ingredients+".\nsuppose we have a medium sustainable recipe "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['title'].values[0]+" composed of "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['ingredients'].values[0]+" which is readable at url "+dataset_mid_sustainble.loc[[mid_sus_max_index]]['url'].values[0]+" and a fully stustainable recipe "+dataset_sustainble.loc[[sus_max_index]]['title'].values[0]+"composed of "+dataset_sustainble.loc[[sus_max_index]]['ingredients'].values[0]+" which is readable at url "+dataset_sustainble.loc[[sus_max_index]]['url'].values[0]+". \nWrite a text that suggest, reffering the user's ingredients only if present in recipes, to consume the first recipe and the second if he/she refer a more sustainable recipe.\nYou must point out that the second recipe is more sustainable.\nBoth suggestion must refer to the url in order to made possibile for user to read the full recipes.\nIf you refer to recipes ingredients use only the ones listed.",
  temperature=0.8,
  max_tokens=1200
)
print(response['choices'][0]['text'])




If you're looking for a tasty breakfast treat, why not try a Fruit and Malt Oat Shake? This delicious recipe contains oats, cow's milk, banana and semi-sweet baking chips. All of your ingredients are included in this yummy shake, and you can find the full recipe at http://www.food.com/recipe/fruit-and-malt-oat-shake-463414. For an even more sustainable option, you can try an Oatmeal and Bananas Breakfast (Baby Food). This recipe also includes oats, cow's milk, and banana. All of your ingredients are present and it's a great way to be more eco-friendly. You can find the full recipe at http://www.food.com/recipe/oatmeal-and-bananas-breakfast-baby-food-52539.
